version: "2"

services:
  framegallery:
    image: framegallery:latest
    container_name: fg
    ports:
      - "8080:80" #change if needed
    environment:
      - CORS_ALLOWED_ORIGIN=http://localhost:8080 #replace with your domain
      - BACKEND_MAX_FILE_SIZE=50MB
      - NGINX_MAX_FILE_SIZE=50m
    volumes:
      - fg-images:/upload-dir
      - fg-db:/fg-db

volumes:
 fg-images:
 fg-db:
